### ISSUE TITLE
how to set table on Database ? 

### ISSUE THREAD

**Issue by reactmorelab** [AyraHikari/EmiliaHikari#4]
How to set table on database , posible give me example structur sql ?

**Comment by AyraHikari** [comment]
What "set table"?
Install sql?
Create table?

**Comment by reactmorelab** [comment]
sorry it turns out that this automatically creates a table right, i use postgres its work 
but after i tried connecting with mysql in phpmyadmin always got an error Can't load plugin: sqlalchemy.dialects: MySQLdb

mysqldb://oxygente_admin:mypass@mydomain:myport/oxygen_emilia_bot

**Comment by AyraHikari** [comment]
No, you must using postgresql instead of mysql.
You can read [english guide here](https://github.com/AyraHikari/EmiliaHikari/blob/master/README.en.md)

URL from postgres should be:
postgresql://username:password@host_name:port/database_name

**Comment by reactmorelab** [comment]
owh i see,  can make request to support mysql ? 

and how to set webhook sir ?

**Comment by ProtoChuz** [comment]
@oxygenfox emila doesnt use webhook :/

**Comment by AyraHikari** [comment]
No, need rebase db to make support mysql.
Also webhook is not support

**Comment by AyraHikari** [comment]
No, it will never use mysql.
To use webhook:
- Do make env var or config for WEBHOOK, and URL. Ex:
WEBHOOK = True
URL = "https://localhost:80/mywebhook"
