### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by gupta-vipin** [AyraHikari/EmiliaHikari#5]
I wanna clone your repo and I need help in deploying it on heroku or any server you say.Will you please please help me.

If you say, I can PM on you telegram.

**Comment by Devp73** [comment]
This is not a issue man

**Comment by AyraHikari** [comment]
See [README English](https://github.com/AyraHikari/EmiliaHikari/blob/master/README.en.md)

If need more help, you can ask in this issue
